---
- name: Ensure zsh is installed when configured
  package:
    name: zsh
    state: present
  become: yes
  when: shell_provider == '/bin/zsh'
  tags: shell

- name: set the users shell
  user:
    name: "{{ shell_user }}"
    shell: "{{ shell_provider }}"
  become: yes
  tags: shell

- name: debug list of users
  shell: "cut -d: -f1 /etc/passwd"
  register: user_list

- name: debug output of users
  debug:
    msg: "{{ user_list }}"

- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ shell_zsh_required_packages }}"
  when: shell_provider == '/bin/zsh'
  tags: shell

- name: "Install oh-my-zsh when configured"
  shell: "{{ shell_install_oh_my_zsh_command }}"
  args:
    chdir: "{{ shell_user_home }}/"
    creates: "{{ shell_user_home }}/.oh-my-zsh"
  register: oh_my_zsh
  become_user: "{{ deployment_ssh_user }}"
  when: shell_provider == '/bin/zsh'
  tags: shell

- name: "Debug oh_my_zsh"
  debug:
    msg: "{{ oh_my_zsh }}"

- name: "Create .zshrc file when zsh is installed"
  template:
    src: ".zshrc.j2"
    dest: "{{ shell_user_home }}/.zshrc"
    owner: "{{ deployment_ssh_user }}"
    group: "www-data"
  become: yes
  tags: shell

- name: "Change umask for {{ shell_user }} bash"
  lineinfile:
    path: "{{ shell_user_home }}/.bashrc"
    regexp: "^umask"
    line: "umask 002"
  become: yes
  when: shell_provider == '/bin/bash'
  tags: shell
